[github link](https://github.com/blackdew/tensorflow1)

In [10]:
import pandas as pd
import tensorflow as tf

# 1. 데이터 준비

In [2]:
lemonade = pd.read_csv('lemonade.csv')
lemonade

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50

In [3]:
boston = pd.read_csv('boston.csv')
boston

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [4]:
iris = pd.read_csv('iris.csv')
iris

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
0     5.1  3.5    1.4   0.2     setosa
1     4.9  3.0    1.4   0.2     setosa
2     4.7  3.2    1.3   0.2     setosa
3     4.6  3.1    1.5   0.2     setosa
4     5.0  3.6    1.4   0.2     setosa
..    ...  ...    ...   ...        ...
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica

[150 rows x 5 columns]

In [5]:
print(lemonade.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)


In [27]:
# 컬럼이름 출력
print(lemonade.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [29]:
iris_encoding = pd.get_dummies(iris)
iris_encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [30]:
X = iris_encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y = iris_encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(X.shape, y.shape)

(150, 4) (150, 3)


In [31]:
iris_encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

# 모델의 구조

In [36]:
X_input = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X_input)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y_output = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X_input, Y_output)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [37]:
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


# 모델의 학습

In [38]:
#model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(X, y, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 1.0456 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0254 - accuracy: 0.3400
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0075 - accuracy: 0.4400
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9911 - accuracy: 0.5067
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9720 - accuracy: 0.5867
Epoch 6/100
5/5 [==============================] - 0s 5ms/step - loss: 0.9519 - accuracy: 0.6933
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9303 - accuracy: 0.6933
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9067 - accuracy: 0.7667
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8828 - accuracy: 0.8200
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8568 - accuracy: 0.7667
Epoch 11/100
5/5 [===========

# 모델의 이용

In [39]:
# 4. 모델을 이용합니다
print(model.predict(X[0:5]))
# 종속변수 확인
print(y[0:5])

[[9.9997067e-01 2.9330218e-05 7.5487208e-09]
 [9.9973661e-01 2.6333798e-04 4.2853390e-08]
 [9.9992573e-01 7.4202653e-05 3.3196059e-08]
 [9.9965084e-01 3.4903520e-04 1.3109562e-07]
 [9.9997807e-01 2.1988229e-05 8.4630853e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [41]:
# 모델의 수식 확인
print(model.get_weights())

[array([[-0.36232078,  0.7684932 ,  0.0173253 ,  0.1977645 ,  0.6721117 ,
         0.573933  , -0.2126648 ,  0.48371172],
       [ 0.26080912, -0.00344209, -0.01647413, -0.03490474, -0.64999   ,
        -0.7590039 , -0.02291995,  0.4429687 ],
       [ 0.37307227, -0.68076354, -0.34917513, -0.15281112,  0.53723985,
         0.34800828,  0.22218864, -0.3670107 ],
       [ 0.8345953 ,  0.23123533, -0.5446936 , -0.1851367 , -0.18503293,
        -0.04015733,  0.8053701 , -0.22556989]], dtype=float32), array([-0.04352738,  0.21484762,  0.18983041,  0.13576692,  0.03876247,
       -0.06139423,  0.13329732,  0.28506187], dtype=float32), array([[ 0.00903327,  0.17712797,  0.74992925, -0.01282943, -0.49715114,
        -0.40335244, -0.5303853 , -0.64407957],
       [-0.41181168,  0.17298716, -0.09300851,  0.8768665 ,  0.30388105,
         0.6232342 ,  0.49033007,  0.06228764],
       [ 0.29013556,  0.36606506,  0.48740983, -0.56871367, -0.01286453,
        -0.574206  , -0.05223751, -0.42331013],
