[github link](https://github.com/blackdew/tensorflow1)

In [10]:
import pandas as pd
import tensorflow as tf

# 1. 데이터 준비

In [2]:
lemonade = pd.read_csv('lemonade.csv')
lemonade

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50

In [3]:
boston = pd.read_csv('boston.csv')
boston

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [4]:
iris = pd.read_csv('iris.csv')
iris

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
0     5.1  3.5    1.4   0.2     setosa
1     4.9  3.0    1.4   0.2     setosa
2     4.7  3.2    1.3   0.2     setosa
3     4.6  3.1    1.5   0.2     setosa
4     5.0  3.6    1.4   0.2     setosa
..    ...  ...    ...   ...        ...
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica

[150 rows x 5 columns]

In [5]:
print(lemonade.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)


In [27]:
# 컬럼이름 출력
print(lemonade.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [29]:
iris_encoding = pd.get_dummies(iris)
iris_encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [30]:
X = iris_encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y = iris_encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(X.shape, y.shape)

(150, 4) (150, 3)


In [31]:
iris_encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

# 모델의 구조

In [32]:
X_input = tf.keras.layers.Input(shape=[4])
Y_output = tf.keras.layers.Dense(3, activation='softmax')(X_input)
model = tf.keras.models.Model(X_input, Y_output)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

# 모델의 학습

In [33]:
#model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(X, y, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 5.5214 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 5.3650 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 5.2512 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 5.1522 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 5.0589 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 4.9677 - accuracy: 0.3333
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 4.8805 - accuracy: 0.3333
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 4.7951 - accuracy: 0.3333
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 4.7119 - accuracy: 0.3333
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 4.6302 - accuracy: 0.3333
Epoch 11/100
5/5 [===========

# 모델의 이용

In [34]:
# 4. 모델을 이용합니다
print(model.predict(X[0:5]))
# 종속변수 확인
print(y[0:5])

[[0.7036555  0.246197   0.05014746]
 [0.67883766 0.24787883 0.07328353]
 [0.68286675 0.25287497 0.06425835]
 [0.63316655 0.28838047 0.07845291]
 [0.69573545 0.25598717 0.04827735]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [35]:
# 모델의 수식 확인
print(model.get_weights())

[array([[ 0.42727396,  0.00686185,  0.02463854],
       [ 0.20921753,  0.29195246, -0.46027818],
       [-0.8932829 , -0.02736302, -0.05358406],
       [-1.023183  , -1.2029307 , -0.18261777]], dtype=float32), array([-0.02727837, -0.39924404,  0.38438493], dtype=float32)]
